source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SevenPass_Example' do
  pod "SevenPass", :path => "../"
  pod "OAuthSwift", :git => "https://github.com/p7s1-ctf/OAuthSwift.git", :branch => "p7-changes"
end

target 'SevenPass_Tests' do
  pod "SevenPass", :path => "../"

  pod 'Quick', '~> 0.8.0'
  pod 'Nimble', '3.0.0'
end
