source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SevenPassSDK_Example' do
  pod "SevenPassSDK", :path => "../"
end

target 'SevenPassSDK_Tests' do
  pod "SevenPassSDK", :path => "../"

  pod 'Quick', '~> 0.10.0'
  pod 'Nimble', '~> 5.1.0'
end
